{% set python_min = "3.10" %}
{% set name = "txl-cell" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_cell-{{ version }}.tar.gz
  sha256: 5e64b96b05d1c5222337e55d8bf684e5fe4adffae42e54923b6f23cfa9a2eb68

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl =0.3.2
    - pycrdt >=0.10.9,<0.13.0

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - txl_cell

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/cell
  summary: TXL plugin for a cell
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/cell
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
