{% set name = "txl-cell" %}
{% set version = "0.2.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_cell-{{ version }}.tar.gz
  sha256: 9ee1b672dcccffbe5820b32d83d2e66bac3c0c37115976e3460c7f68157c25a9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - txl >=0.2.18,<0.3.0
    - pycrdt >=0.10.9,<0.11.0

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - txl_cell

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/cell
  summary: TXL plugin for a cell
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/cell
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
