{% set name = "txl-cell" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/txl_cell-{{ version }}.tar.gz
  sha256: 8e03539f869d32be87d4c228aeb6de204e3533ed88d9bb67e14183cf9da594b1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - txl >=0.2.18,<0.3.0
    - pycrdt >=0.8.11,<0.9.0

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - txl_cell

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/cell
  summary: TXL plugin for a cell
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/cell
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
