{% set name = "txl-cell" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/txl_cell-{{ version }}.tar.gz
  sha256: 66a2359a7a9dec70c088e0d00e5601be3116e40c81ccc6de0ed964efc6eda3a9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - txl
    - pycrdt >=0.8.11,<0.9.0

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - txl_cell

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/cell
  summary: TXL plugin for a cell
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/cell
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
